name: Pipeline
run-name: Push to ${{github.action_path}} by @${{github.actor}}

on: 
    push:
        branches: [ main ]

jobs:
    format:
        runs-on: ubuntu-latest
        steps:
            - name: Check formatting
              run: cargo fmt --check
            - name: Print Congrats
              run: echo Congrats!